### ISSUE TITLE
dvi: GPDI_Dn and GPDI_CLK capacitor values

### ISSUE THREAD

**Issue by pu-cc** [intergalaktik/Extension_Boards_for_Olimex_GateMate#3]
I really like this extension!

Could you share the reasoning behind choosing 220nF for the AC coupling? For high-speed signals like DVI, I would consider changing it to 100nF to avoid excessive attenuation. 100nF is how we tested it on our platforms.

![image](https://github.com/user-attachments/assets/029d5bd9-eb81-493b-90ff-0cf7358fddd4)

**Comment by goran-mahovlic** [comment]
220nF is also working good - but yes I can change to lower.
I have copy pasted old version - I would say at last revision we are down to 22nF

As I have plenty of 100nF that sounds as a best value to go with...
