### ISSUE TITLE
camIO: no support for LP modes and possible saving of U1

### ISSUE THREAD

**Issue by pu-cc** [intergalaktik/Extension_Boards_for_Olimex_GateMate#4]
Great idea for an extension!
This is more of a summary of some of my thoughts:

To support LP (single-ended) mode as well, we would have to use an additional bank that is configured to 1.2V.
It would be interesting to investigate whether we could use the entire bank with 1.2V, i.e. for both the single-ended and the differential inputs.

The Raspberry Pi Camera pull-ups `SCL` and `SDA` to 1.8V. But, thanks to the MOSFET, we could also manage without `U1` with pull-ups to 1.2V or whatever the GPIO voltage is. What do you think?
![image](https://github.com/user-attachments/assets/d38b24fb-3ae0-4ea1-bd54-ea7a74cd0e98)*
(* [reference schematic](https://datasheets.raspberrypi.com/camera/camera-module-2-schematics.pdf))

Btw., I assume that the global names are still there by mistake:
![image](https://github.com/user-attachments/assets/a9d0089d-db43-4cb5-9256-1832a48cfb19)

**Comment by goran-mahovlic** [comment]
Tnx!

You are right, I2C translation chip is not needed, I just assumed camera side, and was wrong :)
As you described, we just need PULL UP to our low voltage level.

2. that is just label converted to text - so nothing important, will change to just SDA/SCL

**Comment by goran-mahovlic** [comment]
>> It would be interesting to investigate whether we could use the entire bank with 1.2V, i.e. for both the single-ended and the differential inputs.

oooo - no I think I get it  - you are suggesting to use remaining pins and connect them over resistor to P lines on CAM?

**Comment by pu-cc** [comment]
> oooo - no I think I get it - you are suggesting to use remaining pins and connect them over resistor to P lines on CAM?

Almost :) We need both `*_N` and `*_P` in LP mode, as it transmits information such as HS-request etc. (LP-11, LP-01, LP-10 and LP-00).

Basically like this:
![image](https://github.com/user-attachments/assets/a0ed4816-cd7b-4bb9-8fc6-dc1f2859c32c)
With `R{1,2,4,5,6,8}=100R` and `R{3,7,9}=150R` -- these are the values ​​from our evaluation with the HS bank at 2.5V and the LP bank at 1.2V.

**Comment by goran-mahovlic** [comment]
@pu-cc could you check current schematic?

Now all 4 pairs have added LP on Positive side I think this could work as those are slow signals and we can always get N with just ~P.

As for R{3,7,9}=150R GateMate does not have internal termination, as that is better then terminate on extension board?

Just in case I can add termination resistors, and we can remove them and check if it is better without them.

**Comment by pu-cc** [comment]
> could you check current schematic?

Sure, can you please push the latest schematic, or do you refer to 0009ad7?

> I think this could work as those are slow signals and we can always get N with just ~P

Not sure if I got this wrong, but `N` is not just `~P`. That's why we need both LP signals.
![image](https://github.com/user-attachments/assets/f0f7b8a6-7400-4e2d-88aa-c41f13da8e72)*
(* [reference](https://www.zephray.me/post/mipi_dsi_note/))

> GateMate does not have internal termination,

GateMate indeed has an internal 100R termination resistor in LVDS mode. But it's exactly as you say, we wanted to have the external resistors for additional testing.

**Comment by goran-mahovlic** [comment]
@pu-cc I have placed termination resistor like on your schematics

Yes, from this picture it could be that you need P and N LP pins - but you only need P CLK pin?

![image](https://github.com/user-attachments/assets/a3c42b6e-96e2-4d0e-9f38-3c631f4424d5)

If so I will have enough pins for the two data lines setup - like this

![Screenshot from 2024-12-10 22-41-10](https://github.com/user-attachments/assets/6b00dea7-0de0-4e95-b907-c46e8fdf55c5)
